#!/usr/bin/env bash

$CAUR_PUSH 'source /etc/profile'
$CAUR_PUSHgroupadd flutterusers
$CAUR_PUSHgpasswd -a $USER flutterusers
$CAUR_PUSH chown -R $USER:flutterusers /opt/flutter
$CAUR_PUSHchmod -R g+w /opt/flutter/
