#!/usr/bin/env sh

# mangle replaces directive
sed -E 's&^(\s*)(replaces\+?=)&\1 _ignore_\2&g' -i PKGBUILD

# add conflicts
sed -E \
  -e 's&^(_package\(\) \{)$&\1\n  conflicts=(linux-xanmod-lts)&' \
  -e 's&^(_package-headers\(\) \{)$&\1\n  conflicts=(linux-xanmod-lts-headers)&' \
  -i PKGBUILD
