#!/usr/bin/env sh

# save pkgname, pkgver
_pkgname=$(sed -En 's/^\s*(pkgname=.*)$/\1/p' PKGBUILD)

# clear PKGBUILD
truncate -s 0 PKGBUILD

# write pkgname
[[ "$_pkgname" == "pkgname=art-rawconverter" ]] && echo "$_pkgname" >> PKGBUILD
