#!/usr/bin/env sh

# comply with font package guidelines
sed -E -e 's&^(\s*)(depends\+?=)&\1 _ignore_\2&g' -i PKGBUILD
sed -E -e 's&^(\s*)(makedepends\+?=)&\1 _ignore_\2&g' -i PKGBUILD
sed -E -e 's&^(\s*)(install\+?=)&\1 _ignore_\2&g' -i PKGBUILD
