#!/usr/bin/env sh
# $CAUR_PUSH 'pacman -S --noconfirm flutter-bin'
# $CAUR_PUSH 'usermod -aG flutterusers main-builder'
# $CAUR_PUSH 'chown -R main-builder:main-builder /opt/flutter'

_chaotic_pkgver=1.20.0
_chaotic_pkgrel=1
_chaotic_shasum='c8a0462a1729fc9feb7213af2266cc230dc61fad589b2507cdb4e8144a5fef19'

_old_pkgver=$(sed -En '/^\s*pkgver=.*[0-9].*/ s/.*\=//p' PKGBUILD)

if [[ "$(vercmp "$_chaotic_pkgver" "$_old_pkgver")" -gt 0 ]] ; then
  sed -E \
    -e 's@^(\s*pkgver)=.*$@\1='"$_chaotic_pkgver"'@' \
    -e 's@^(\s*pkgrel)=.*$@\1='"$_chaotic_pkgrel"'@' \
    -e 's@^(\s*sha256sums)=.*(\)?)$@\1=('"$_chaotic_shasum"'\2@' \
    -e '/^\s*patch .*$/d' \
    -i PKGBUILD
fi
