#!/usr/bin/env sh

# mangle replaces directive
sed -E 's&^(\s*)(replaces\+?=)&\1 _ignore_\2&g' -i PKGBUILD

# don't make -docs
sed -E -i PKGBUILD \
  -e 's&^(\s*)(.*make htmldocs)$&\1 : # \2&' \
  -e '/^\s*"\$.*-docs.*"$/d'
