#!/usr/bin/env sh

# mangle replaces directive
sed -E 's&^(\s*)(replaces\+?=)&\1 _ignore_\2&g' -i PKGBUILD

# don't make -docs
sed -E -i PKGBUILD \
  -e '/^\s*.*make htmldocs$/d' \
  -e '/^\s*"$pkgbase-docs"$/d'

# rename pkgbase
sed -E -i PKGBUILD \
  -e 's&^(pkgbase=.*)$&\1-mainline-v3&'
