#!/usr/bin/env bash

if [ -n "${CAUR_PUSH:-}" ]; then
	$CAUR_PUSH 'yes | pacman -S pacman-git'
else
	echo 'This ocean looks dry'
	exit 17
fi
mv /etc/pacman.conf.pacsave /etc/pacman.conf
mv /etc/makepkg.conf.pacsave /etc/makepkg.conf
